name: Bug Report
description: A report of an error in a recent systemd version
title: "[Bug]: "
labels: ["bug 🐛"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: version
    attributes:
      label: Version
      description: |
        Systemd version the issue has been seen with
        Do not submit bug reports about anything but the two most recently released *major* systemd versions upstream!
        If there have been multiple stable releases for that major version, please consider updating to a recent one before reporting an issue.
        When using a distro package, please make sure that the version reported is meaningful for upstream.
        See https://github.com/systemd/systemd-stable/tags for the list of most recent releases.
        For older version please use distribution trackers (see https://systemd.io/CONTRIBUTING#filing-issues).
      placeholder: v251
    validations:
      required: true
    
  - type: input
    id: distro
    attributes:
      label: Distribution
      description: Used distribution and it's version
      placeholder: Fedora 37
    validations:
      required: true
  
  - type: input
    id: kernel
    attributes:
      label: Linux kernel
      description: |
        Linux kernel version used (`uname -a`)
        Make sure to enclose the pasted kernel version in `backticks`, so that GitHub doesn't convert the `#` character typically included in it into a reference to old GitHub issues.
      placeholder: 5.17.12-300.fc36.ppc64le
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      description: CPU architecture issue was seen on
      options:
        - aarch64
        - i686
        - ppc64le
        - s390x
        - x86_64
    validations:
      required: false

  - type: textarea
    id: expected-behaviour
    attributes:
      label: What is expected?
      description: Expected behaviour you didn't see
    validations:
      required: true

  - type: textarea
    id: unexpected-behaviour
    attributes:
      label: What happened?
      description: Unexpected behaviour you saw
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the problem
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: |
        Additional program output to the terminal or log subsystem illustrating the issue.
        This will be automatically formatted into code, so no need for backticks.
      placeholder: |
        Please paste relevant program terminal or journal output here, ideally
        when generated in debug mode (try setting the SYSTEMD_LOG_LEVEL=debug
        environment variable). For very long copy/pasted data consider using a
        service like https://gist.github.com/. Where copy/paste is not possible
        (for example early boot or late shutdown), a photo of the screen might do
        too, but text is always much preferred.
      render: shell
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
