name: Phase of Development
description: A report of an error in a recent systemd version
labels: ["bug 🐛"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: Phase-of-development
    attributes:
      label: Phase of development
      multiple: false
      options:
        - 'Phase-1'
        - 'Phase-2'
        - 'Phase-3'
        
  - type: checkboxes
    id: Platform-work-question
    attributes:
      label: Platform work
      description: "Is this platform work that could be shared across multiple themes?"
      options:
        - label: Check box if YES
